name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker image and deploy to Minikube
    steps:
    - uses: actions/checkout@v2

    - name: Start Minikube
      uses: medyagh/setup-minikube@master

    - name: Try the cluster!
      run: kubectl get pods -A
x
    - name: Build Docker image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t devopshint/node-app:latest .
        echo "Verifying images:"
        docker images

    - name: Deploy to Minikube
      run: kubectl apply -f k8s-node-app.yaml

    - name: Check pod status
      run: kubectl get pods -o 
      
    - name: Get pod logs
      run: |
        POD_NAME=$(kubectl get pod -l app=nodejs-app -o jsonpath="{.items[0].metadata.name}")
        kubectl logs $POD_NAME

    - name: Test service URLs
      run: |
        minikube service list
        minikube service nodejs-app --url